import { StockAdjustment } from "@/types/inventory";

export const mockStockAdjustments: StockAdjustment[] = [
  {
    id: "adj-001",
    adjustmentNumber: "ADJ-2025-001",
    date: new Date("2025-10-15"),
    type: "physical_count",
    itemId: "INV-001",
    itemName: "Paracetamol 500mg Tablets",
    batchNumber: "PARA2024-A01",
    quantityBefore: 1000,
    quantityAfter: 985,
    difference: -15,
    reason: "Physical count discrepancy - 15 tablets missing",
    performedBy: "Carmen Lopez",
    approvedBy: "Marisa Gonzales",
    remarks: "Possible theft or misplacement during inventory check",
    createdAt: new Date("2025-10-15"),
  },
  {
    id: "adj-002",
    adjustmentNumber: "ADJ-2025-002",
    date: new Date("2025-10-18"),
    type: "damage",
    itemId: "INV-002",
    itemName: "Amoxicillin 500mg Capsules",
    batchNumber: "AMOX2024-B01",
    quantityBefore: 500,
    quantityAfter: 480,
    difference: -20,
    reason: "Water damage from storage area leak",
    performedBy: "Ana Reyes",
    approvedBy: "Marisa Gonzales",
    remarks: "20 capsules damaged due to roof leak in storage area",
    createdAt: new Date("2025-10-18"),
  },
  {
    id: "adj-003",
    adjustmentNumber: "ADJ-2025-003",
    date: new Date("2025-10-20"),
    type: "expired",
    itemId: "INV-003",
    itemName: "Ibuprofen 400mg Tablets",
    batchNumber: "IBUP2023-C01",
    quantityBefore: 200,
    quantityAfter: 0,
    difference: -200,
    reason: "Batch expired - removed from inventory",
    performedBy: "Carmen Lopez",
    approvedBy: "Marisa Gonzales",
    remarks: "Entire batch expired on Sept 30, 2025 - proper disposal completed",
    createdAt: new Date("2025-10-20"),
  },
  {
    id: "adj-004",
    adjustmentNumber: "ADJ-2025-004",
    date: new Date("2025-10-22"),
    type: "correction",
    itemId: "INV-004",
    itemName: "Vitamin C 500mg Tablets",
    batchNumber: "VITC2024-D01",
    quantityBefore: 100,
    quantityAfter: 105,
    difference: +5,
    reason: "Data entry correction - previous count was inaccurate",
    performedBy: "Maria Santos",
    approvedBy: "Marisa Gonzales",
    remarks: "System error in previous count entry, corrected after verification",
    createdAt: new Date("2025-10-22"),
  },
  {
    id: "adj-005",
    adjustmentNumber: "ADJ-2025-005",
    date: new Date("2025-10-25"),
    type: "physical_count",
    itemId: "INV-005",
    itemName: "Oral Rehydration Salts",
    batchNumber: "ORS2024-E01",
    quantityBefore: 300,
    quantityAfter: 298,
    difference: -2,
    reason: "Monthly physical count - minor discrepancy",
    performedBy: "Carmen Lopez",
    approvedBy: "Marisa Gonzales",
    remarks: "2 packets unaccounted for - likely documentation error",
    createdAt: new Date("2025-10-25"),
  },
  {
    id: "adj-006",
    adjustmentNumber: "ADJ-2025-006",
    date: new Date("2025-10-26"),
    type: "other",
    itemId: "INV-006",
    itemName: "Digital Thermometers",
    batchNumber: "TEMP2024-F01",
    quantityBefore: 50,
    quantityAfter: 48,
    difference: -2,
    reason: "Returned to supplier due to calibration issues",
    performedBy: "Ana Reyes",
    approvedBy: "Marisa Gonzales",
    remarks: "2 units found to be defective during quality check",
    createdAt: new Date("2025-10-26"),
  },
  {
    id: "adj-007",
    adjustmentNumber: "ADJ-2025-007",
    date: new Date("2025-10-27"),
    type: "damage",
    itemId: "INV-007",
    itemName: "Multivitamins for Adults",
    batchNumber: "MUL2024-G01",
    quantityBefore: 150,
    quantityAfter: 145,
    difference: -5,
    reason: "Packaging damage during transport",
    performedBy: "Maria Santos",
    approvedBy: "Pending Approval",
    remarks: "5 bottles with cracked caps - unable to sell or distribute",
    createdAt: new Date("2025-10-27"),
  }
];