import { InventoryItem, InventoryTransaction, Batch } from "@/types/inventory";

export const mockBatches: Batch[] = [
  {
    id: "BATCH-001",
    batchNumber: "PARA2025-A01",
    itemId: "INV-001",
    itemName: "Paracetamol 500mg Tablets",
    expiryDate: new Date("2027-06-30"),
    quantity: 850,
    receivedDate: new Date("2025-10-24"),
    supplier: "MediPharm Solutions Inc.",
    wrrNumber: "WRR-2025-001",
    location: "Main Pharmacy Storage - Shelf A1",
    status: "active",
  },
  {
    id: "BATCH-002",
    batchNumber: "AMOX2025-B01",
    itemId: "INV-002",
    itemName: "Amoxicillin 500mg Capsules",
    expiryDate: new Date("2027-05-15"),
    quantity: 450,
    receivedDate: new Date("2025-10-24"),
    supplier: "MediPharm Solutions Inc.",
    wrrNumber: "WRR-2025-001",
    location: "Main Pharmacy Storage - Shelf A2",
    status: "active",
  },
  {
    id: "BATCH-003",
    batchNumber: "PARA2024-Z01",
    itemId: "INV-001",
    itemName: "Paracetamol 500mg Tablets",
    expiryDate: new Date("2026-03-15"),
    quantity: 120,
    receivedDate: new Date("2024-09-10"),
    supplier: "HealthCare Supplies Co.",
    wrrNumber: "WRR-2024-015",
    location: "Main Pharmacy Storage - Shelf A1",
    status: "expiring_soon",
  },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "INV-001",
    itemCode: "MED-001",
    itemName: "Paracetamol 500mg Tablets",
    category: "Pain Relief",
    subType: "supplied",
    unit: "tablets",
    totalQuantity: 970,
    availableQuantity: 970,
    reorderLevel: 500,
    batches: [mockBatches[0], mockBatches[2]],
    status: "active",
    location: "Main Pharmacy Storage - Shelf A1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2025-10-24"),
  },
  {
    id: "INV-002",
    itemCode: "MED-002",
    itemName: "Amoxicillin 500mg Capsules",
    category: "Antibiotics",
    subType: "supplied",
    unit: "capsules",
    totalQuantity: 450,
    availableQuantity: 450,
    reorderLevel: 300,
    batches: [mockBatches[1]],
    status: "active",
    location: "Main Pharmacy Storage - Shelf A2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2025-10-24"),
  },
  {
    id: "INV-003",
    itemCode: "MED-003",
    itemName: "Ibuprofen 400mg Tablets",
    category: "Pain Relief",
    subType: "supplied",
    unit: "tablets",
    totalQuantity: 250,
    availableQuantity: 250,
    reorderLevel: 400,
    batches: [
      {
        id: "BATCH-004",
        batchNumber: "IBUP2024-X01",
        itemId: "INV-003",
        itemName: "Ibuprofen 400mg Tablets",
        expiryDate: new Date("2026-08-30"),
        quantity: 250,
        receivedDate: new Date("2024-11-05"),
        supplier: "Generic Drug Store Wholesale",
        wrrNumber: "WRR-2024-020",
        location: "Main Pharmacy Storage - Shelf B1",
        status: "low_stock",
      },
    ],
    status: "low_stock",
    location: "Main Pharmacy Storage - Shelf B1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2025-10-15"),
  },
  {
    id: "INV-004",
    itemCode: "MED-004",
    itemName: "Cetirizine 10mg Tablets",
    category: "Antihistamines",
    subType: "donated",
    unit: "tablets",
    totalQuantity: 0,
    availableQuantity: 0,
    reorderLevel: 200,
    batches: [],
    status: "out_of_stock",
    location: "Main Pharmacy Storage - Shelf B2",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2025-10-10"),
  },
  {
    id: "INV-005",
    itemCode: "MED-005",
    itemName: "Rifampicin 150mg Tablets",
    category: "TB Program",
    subType: "supplied",
    unit: "tablets",
    totalQuantity: 1500,
    availableQuantity: 1500,
    reorderLevel: 1000,
    batches: [
      {
        id: "BATCH-005",
        batchNumber: "RIFA2025-C01",
        itemId: "INV-005",
        itemName: "Rifampicin 150mg Tablets",
        expiryDate: new Date("2027-12-31"),
        quantity: 1500,
        receivedDate: new Date("2025-10-28"),
        supplier: "HealthCare Supplies Co.",
        wrrNumber: "WRR-2025-002",
        location: "TB Program Storage - Shelf A",
        status: "active",
      },
    ],
    status: "active",
    location: "TB Program Storage - Shelf A",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2025-10-28"),
  },
];

export const mockInventoryTransactions: InventoryTransaction[] = [
  {
    id: "TRX-001",
    transactionNumber: "TRX-2025-001",
    date: new Date("2025-10-24"),
    type: "warehouse_receiving",
    itemId: "INV-001",
    itemName: "Paracetamol 500mg Tablets",
    itemSubType: "supplied",
    batchNumber: "PARA2025-A01",
    quantity: 1000,
    beginningQuantity: 120,
    endingQuantity: 1120,
    expiryDate: new Date("2027-06-30"),
    referenceNumber: "WRR-2025-001",
    location: "Main Pharmacy Storage - Shelf A1",
    performedBy: "GSO Staff Carmen Lopez",
    approvedBy: "Marisa Gonzales",
    remarks: "Stock received from PO-2025-001",
    createdAt: new Date("2025-10-24"),
  },
  {
    id: "TRX-002",
    transactionNumber: "TRX-2025-002",
    date: new Date("2025-10-25"),
    type: "dispense",
    itemId: "INV-001",
    itemName: "Paracetamol 500mg Tablets",
    itemSubType: "supplied",
    batchNumber: "PARA2024-Z01",
    quantity: -50,
    beginningQuantity: 1120,
    endingQuantity: 1070,
    expiryDate: new Date("2026-03-15"),
    location: "Main Pharmacy Storage - Shelf A1",
    performedBy: "Pharmacist Ana Reyes",
    remarks: "Dispensed to outpatient department",
    createdAt: new Date("2025-10-25"),
  },
  {
    id: "TRX-003",
    transactionNumber: "TRX-2025-003",
    date: new Date("2025-10-26"),
    type: "dispense",
    itemId: "INV-002",
    itemName: "Amoxicillin 500mg Capsules",
    itemSubType: "supplied",
    batchNumber: "AMOX2025-B01",
    quantity: -50,
    beginningQuantity: 500,
    endingQuantity: 450,
    expiryDate: new Date("2027-05-15"),
    location: "Main Pharmacy Storage - Shelf A2",
    performedBy: "Pharmacist Ana Reyes",
    remarks: "Prescribed by Dr. Maria Santos",
    createdAt: new Date("2025-10-26"),
  },
  {
    id: "TRX-004",
    transactionNumber: "TRX-2025-004",
    date: new Date("2025-10-27"),
    type: "adjustment",
    itemId: "INV-001",
    itemName: "Paracetamol 500mg Tablets",
    itemSubType: "supplied",
    batchNumber: "PARA2025-A01",
    quantity: -100,
    beginningQuantity: 1070,
    endingQuantity: 970,
    location: "Main Pharmacy Storage - Shelf A1",
    performedBy: "GSO Staff Carmen Lopez",
    approvedBy: "Marisa Gonzales",
    remarks: "Physical count adjustment - damaged packaging",
    createdAt: new Date("2025-10-27"),
  },
];

