import { LGU, Facility, LGUUser } from "@/types/lgu";

export const mockLGUs: LGU[] = [
  {
    id: "lgu-001",
    code: "DLG",
    name: "Dalaguete Municipality",
    region: "Central Visayas",
    province: "Cebu",
    municipality: "Dalaguete",
    barangays: [
      "Poblacion",
      "Lenchuan",
      "Balud",
      "Tapon",
      "Casay",
      "Tubod",
      "Ablayan",
      "Bulak",
      "Manlayag",
      "Da-o",
      "Mantalongon",
      "Tapon",
      "Ablayan",
      "Bulak",
      "Manlayag",
      "Da-o",
      "Mantalongon",
    ],
    contactInformation: {
      address: "Municipal Hall, Poblacion, Dalaguete, Cebu",
      phone: "0912-345-6789",
      email: "contact@dalaguete.gov.ph",
    },
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "lgu-002",
    code: "ARL",
    name: "Argao Municipality",
    region: "Central Visayas",
    province: "Cebu",
    municipality: "Argao",
    barangays: [
      "Poblacion",
      "Binlod",
      "Bogo",
      "Cansuje",
      "Talisay",
      "Canbanua",
    ],
    contactInformation: {
      address: "Municipal Hall, Poblacion, Argao, Cebu",
      phone: "0913-456-7890",
      email: "contact@argao.gov.ph",
    },
    isActive: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-20"),
  },
];

export const mockFacilities: Facility[] = [
  {
    id: "fac-001",
    lguId: "lgu-001",
    facilityCode: "DLG-HOSP",
    name: "Dalaguete District Hospital",
    type: "hospital",
    address: "Poblacion, Dalaguete, Cebu",
    barangay: "Poblacion",
    contactInformation: {
      phone: "0939-123-4567",
      email: "dghospital@dalaguete.gov.ph",
    },
    capacity: {
      beds: 50,
      staff: 35,
    },
    operatingHours: {
      open: "08:00",
      close: "17:00",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    },
    isActive: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "fac-002",
    lguId: "lgu-001",
    facilityCode: "DLG-HC-001",
    name: "Poblacion Health Center",
    type: "health_center",
    address: "Barangay Poblacion, Dalaguete, Cebu",
    barangay: "Poblacion",
    contactInformation: {
      phone: "0939-234-5678",
    },
    capacity: {
      staff: 10,
    },
    operatingHours: {
      open: "07:00",
      close: "16:00",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    },
    isActive: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "fac-003",
    lguId: "lgu-001",
    facilityCode: "DLG-HC-002",
    name: "Mantalongon Health Center",
    type: "health_center",
    address: "Barangay Mantalongon, Dalaguete, Cebu",
    barangay: "Mantalongon",
    contactInformation: {
      phone: "0939-345-6789",
    },
    capacity: {
      staff: 8,
    },
    operatingHours: {
      open: "07:00",
      close: "16:00",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    },
    isActive: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-18"),
  },
];

export const mockLGUUsers: LGUUser[] = [
  {
    id: "user-lgu-001",
    lguId: "lgu-001",
    facilityId: "fac-001",
    username: "dr.marias",
    email: "maria.santos@dalaguete.gov.ph",
    firstName: "Maria",
    lastName: "Santos",
    role: "medical_staff",
    position: "Chief Medical Officer",
    department: "Clinical Services",
    isActive: true,
    lastLogin: new Date("2024-01-15T08:30:00"),
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "user-lgu-002",
    lguId: "lgu-001",
    username: "carmen.lopez",
    email: "carmen.lopez@dalaguete.gov.ph",
    firstName: "Carmen",
    lastName: "Lopez",
    role: "gso_staff",
    position: "GSO Officer",
    department: "General Services Office",
    isActive: true,
    lastLogin: new Date("2024-01-14T14:20:00"),
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "user-lgu-003",
    lguId: "lgu-001",
    facilityId: "fac-002",
    username: "ana.reyes",
    email: "ana.reyes@dalaguete.gov.ph",
    firstName: "Ana",
    lastName: "Reyes",
    role: "medical_staff",
    position: "Nurse",
    department: "Health Center",
    isActive: true,
    lastLogin: new Date("2024-01-15T09:15:00"),
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
];

