import { Patient, MedicalRecord } from "@/types/patient";

export const mockPatients: Patient[] = [
  {
    id: "PAT-001",
    patientId: "2025-001",
    firstName: "Juan",
    middleName: "Santos",
    lastName: "Dela Cruz",
    dateOfBirth: new Date("1985-05-15"),
    age: 40,
    gender: "male",
    address: {
      barangay: "Poblacion",
      municipality: "Dalaguete",
      province: "Cebu",
      zipCode: "6022",
    },
    contactNumber: "+63 912 345 6789",
    email: "juan.delacruz@email.com",
    emergencyContact: {
      name: "Maria Dela Cruz",
      relationship: "Spouse",
      phone: "+63 912 345 6790",
    },
    bloodType: "O+",
    allergies: ["Penicillin"],
    status: "active",
    registrationDate: new Date("2024-01-15"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2025-10-20"),
  },
  {
    id: "PAT-002",
    patientId: "2025-002",
    firstName: "Maria",
    middleName: "Garcia",
    lastName: "Santos",
    dateOfBirth: new Date("1990-08-22"),
    age: 35,
    gender: "female",
    address: {
      barangay: "Mantalongon",
      municipality: "Dalaguete",
      province: "Cebu",
      zipCode: "6022",
    },
    contactNumber: "+63 923 456 7890",
    emergencyContact: {
      name: "Pedro Santos",
      relationship: "Spouse",
      phone: "+63 923 456 7891",
    },
    bloodType: "A+",
    allergies: [],
    status: "active",
    registrationDate: new Date("2024-02-10"),
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2025-10-18"),
  },
  {
    id: "PAT-003",
    patientId: "2024-156",
    firstName: "Pedro",
    middleName: "Luna",
    lastName: "Reyes",
    dateOfBirth: new Date("1955-12-03"),
    age: 69,
    gender: "male",
    address: {
      barangay: "Coro",
      municipality: "Dalaguete",
      province: "Cebu",
      zipCode: "6022",
    },
    contactNumber: "+63 934 567 8901",
    emergencyContact: {
      name: "Rosa Reyes",
      relationship: "Daughter",
      phone: "+63 934 567 8902",
    },
    bloodType: "B+",
    allergies: ["Shellfish", "Aspirin"],
    status: "active",
    registrationDate: new Date("2023-06-20"),
    createdAt: new Date("2023-06-20"),
    updatedAt: new Date("2025-10-25"),
  },
  {
    id: "PAT-004",
    patientId: "2025-045",
    firstName: "Ana",
    middleName: "Cruz",
    lastName: "Lopez",
    dateOfBirth: new Date("2020-03-10"),
    age: 5,
    gender: "female",
    address: {
      barangay: "Consolacion",
      municipality: "Dalaguete",
      province: "Cebu",
      zipCode: "6022",
    },
    contactNumber: "+63 945 678 9012",
    emergencyContact: {
      name: "Carmen Lopez",
      relationship: "Mother",
      phone: "+63 945 678 9012",
    },
    bloodType: "O-",
    allergies: [],
    status: "active",
    registrationDate: new Date("2025-03-10"),
    createdAt: new Date("2025-03-10"),
    updatedAt: new Date("2025-10-15"),
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "MR-001",
    patientId: "PAT-001",
    recordNumber: "MR-2025-001",
    date: new Date("2025-10-20"),
    chiefComplaint: "Fever and headache for 2 days",
    diagnosis: "Viral Upper Respiratory Tract Infection",
    prescriptions: [
      {
        medicationName: "Paracetamol 500mg",
        dosage: "1 tablet",
        frequency: "Every 6 hours",
        duration: "5 days",
      },
    ],
    vitalSigns: {
      bloodPressure: "120/80",
      temperature: 38.5,
      pulseRate: 82,
      respiratoryRate: 18,
      weight: 70,
      height: 170,
    },
    treatmentPlan: "Rest, increase fluid intake, monitor temperature",
    followUpDate: new Date("2025-10-27"),
    attendingPhysician: "Dr. Maria Santos",
    remarks: "Patient advised to return if symptoms worsen",
    createdAt: new Date("2025-10-20"),
    updatedAt: new Date("2025-10-20"),
  },
  {
    id: "MR-002",
    patientId: "PAT-002",
    recordNumber: "MR-2025-002",
    date: new Date("2025-10-18"),
    chiefComplaint: "Prenatal check-up",
    diagnosis: "Pregnancy - 2nd trimester (20 weeks)",
    prescriptions: [
      {
        medicationName: "Prenatal Vitamins",
        dosage: "1 tablet",
        frequency: "Once daily",
        duration: "Until delivery",
      },
      {
        medicationName: "Ferrous Sulfate",
        dosage: "1 tablet",
        frequency: "Once daily",
        duration: "Until delivery",
      },
    ],
    vitalSigns: {
      bloodPressure: "110/70",
      temperature: 36.8,
      pulseRate: 75,
      weight: 58,
      height: 160,
    },
    treatmentPlan: "Regular prenatal check-ups, balanced diet, moderate exercise",
    followUpDate: new Date("2025-11-18"),
    attendingPhysician: "Dr. Maria Santos",
    labResults: "All labs within normal limits",
    remarks: "Mother and baby in good health",
    createdAt: new Date("2025-10-18"),
    updatedAt: new Date("2025-10-18"),
  },
  {
    id: "MR-003",
    patientId: "PAT-003",
    recordNumber: "MR-2025-003",
    date: new Date("2025-10-25"),
    chiefComplaint: "Cough with sputum for 3 weeks",
    diagnosis: "Suspected Tuberculosis - for confirmation",
    prescriptions: [],
    vitalSigns: {
      bloodPressure: "140/90",
      temperature: 37.2,
      pulseRate: 88,
      respiratoryRate: 20,
      weight: 55,
      height: 165,
    },
    treatmentPlan: "Sputum test ordered, chest X-ray requested",
    followUpDate: new Date("2025-11-01"),
    attendingPhysician: "Dr. Maria Santos",
    labResults: "Pending sputum test results",
    remarks: "Patient referred to TB program coordinator",
    createdAt: new Date("2025-10-25"),
    updatedAt: new Date("2025-10-25"),
  },
  {
    id: "MR-004",
    patientId: "PAT-004",
    recordNumber: "MR-2025-004",
    date: new Date("2025-10-15"),
    chiefComplaint: "Routine vaccination",
    diagnosis: "Well child visit",
    prescriptions: [],
    vitalSigns: {
      temperature: 36.5,
      weight: 18,
      height: 110,
    },
    treatmentPlan: "Age-appropriate vaccinations administered",
    followUpDate: new Date("2026-04-15"),
    attendingPhysician: "Nurse Pedro Cruz",
    remarks: "DPT booster and MMR vaccine given. No adverse reactions noted.",
    createdAt: new Date("2025-10-15"),
    updatedAt: new Date("2025-10-15"),
  },
];

