import { PurchaseRequest } from "@/types/purchasing";

export const mockPurchaseRequests: PurchaseRequest[] = [
  {
    id: "PR-001",
    prNumber: "PR-2025-001",
    date: new Date("2025-10-15"),
    requestingDepartment: "Medical Services",
    costCenter: "Outpatient Department",
    status: "approved",
    items: [
      {
        id: "PRI-001",
        itemName: "Paracetamol 500mg Tablets",
        itemCode: "MED-001",
        quantity: 1000,
        unit: "tablets",
        estimatedPrice: 0.50,
        notes: "For general use",
      },
      {
        id: "PRI-002",
        itemName: "Amoxicillin 500mg Capsules",
        itemCode: "MED-002",
        quantity: 500,
        unit: "capsules",
        estimatedPrice: 2.50,
      },
    ],
    requestedBy: "Dr. Maria Santos",
    approvedBy: "Marisa Gonzales",
    approvedDate: new Date("2025-10-16"),
    remarks: "Urgent request due to high demand",
    createdAt: new Date("2025-10-15"),
    updatedAt: new Date("2025-10-16"),
  },
  {
    id: "PR-002",
    prNumber: "PR-2025-002",
    date: new Date("2025-10-20"),
    requestingDepartment: "Pharmacy",
    costCenter: "Pharmacy Department",
    status: "pending",
    items: [
      {
        id: "PRI-003",
        itemName: "Ibuprofen 400mg Tablets",
        itemCode: "MED-003",
        quantity: 800,
        unit: "tablets",
        estimatedPrice: 1.20,
      },
      {
        id: "PRI-004",
        itemName: "Cetirizine 10mg Tablets",
        itemCode: "MED-004",
        quantity: 600,
        unit: "tablets",
        estimatedPrice: 0.80,
      },
      {
        id: "PRI-005",
        itemName: "Surgical Gloves (Medium)",
        itemCode: "SUP-001",
        quantity: 200,
        unit: "pairs",
        estimatedPrice: 5.00,
      },
    ],
    requestedBy: "Pharmacist Ana Reyes",
    remarks: "Monthly stock replenishment",
    createdAt: new Date("2025-10-20"),
    updatedAt: new Date("2025-10-20"),
  },
  {
    id: "PR-003",
    prNumber: "PR-2025-003",
    date: new Date("2025-10-18"),
    requestingDepartment: "TB Program",
    costCenter: "TB Control Program",
    status: "completed",
    items: [
      {
        id: "PRI-006",
        itemName: "Rifampicin 150mg Tablets",
        itemCode: "MED-005",
        quantity: 2000,
        unit: "tablets",
        estimatedPrice: 3.00,
      },
      {
        id: "PRI-007",
        itemName: "Isoniazid 300mg Tablets",
        itemCode: "MED-006",
        quantity: 2000,
        unit: "tablets",
        estimatedPrice: 1.50,
      },
    ],
    requestedBy: "Nurse Pedro Cruz",
    approvedBy: "Marisa Gonzales",
    approvedDate: new Date("2025-10-19"),
    remarks: "DOH Program medicines",
    createdAt: new Date("2025-10-18"),
    updatedAt: new Date("2025-10-22"),
  },
  {
    id: "PR-004",
    prNumber: "PR-2025-004",
    date: new Date("2025-10-22"),
    requestingDepartment: "Medical Services",
    costCenter: "Maternal Health",
    status: "denied",
    items: [
      {
        id: "PRI-008",
        itemName: "Prenatal Vitamins",
        itemCode: "MED-007",
        quantity: 300,
        unit: "bottles",
        estimatedPrice: 150.00,
      },
    ],
    requestedBy: "Midwife Rosa Garcia",
    deniedReason: "Budget constraints - please resubmit next month",
    remarks: "For prenatal care program",
    createdAt: new Date("2025-10-22"),
    updatedAt: new Date("2025-10-23"),
  },
  {
    id: "PR-005",
    prNumber: "PR-2025-005",
    date: new Date("2025-10-25"),
    requestingDepartment: "Admin Office",
    costCenter: "Administration",
    status: "draft",
    items: [
      {
        id: "PRI-009",
        itemName: "Office Supplies (Bond Paper)",
        itemCode: "OFF-001",
        quantity: 50,
        unit: "reams",
        estimatedPrice: 150.00,
      },
      {
        id: "PRI-010",
        itemName: "Printer Ink Cartridges",
        itemCode: "OFF-002",
        quantity: 10,
        unit: "pieces",
        estimatedPrice: 500.00,
      },
    ],
    requestedBy: "Admin Staff Juan Dela Rosa",
    createdAt: new Date("2025-10-25"),
    updatedAt: new Date("2025-10-25"),
  },
];

