import { Supplier } from "@/types/purchasing";

export const mockSuppliers: Supplier[] = [
  {
    id: "SUP-001",
    name: "MediPharm Solutions Inc.",
    code: "MPS001",
    contactPerson: "Juan dela Cruz",
    phone: "+63 32 234 5678",
    email: "sales@medipharm.ph",
    address: "123 Pharmacy St., Cebu City",
    tin: "123-456-789-000",
    taxType: "VAT",
    withholdingTax: 2,
    paymentTerms: "Net 30",
  },
  {
    id: "SUP-002",
    name: "HealthCare Supplies Co.",
    code: "HCS002",
    contactPerson: "Maria Santos",
    phone: "+63 32 345 6789",
    email: "orders@healthcaresupplies.ph",
    address: "456 Medical Ave., Mandaue City",
    tin: "234-567-890-000",
    taxType: "VAT",
    withholdingTax: 2,
    paymentTerms: "Net 45",
  },
  {
    id: "SUP-003",
    name: "PhilMed Distributors",
    code: "PMD003",
    contactPerson: "Pedro Reyes",
    phone: "+63 32 456 7890",
    email: "contact@philmed.ph",
    address: "789 Hospital Rd., Cebu City",
    tin: "345-678-901-000",
    taxType: "Non-VAT",
    withholdingTax: 0,
    paymentTerms: "Net 15",
  },
  {
    id: "SUP-004",
    name: "Generic Drug Store Wholesale",
    code: "GDS004",
    contactPerson: "Ana Cruz",
    phone: "+63 32 567 8901",
    email: "wholesale@genericdrug.ph",
    address: "321 Generics Blvd., Lapu-Lapu City",
    tin: "456-789-012-000",
    taxType: "VAT",
    withholdingTax: 2,
    paymentTerms: "Net 30",
  },
];

