import { WarehouseReceivingReport } from "@/types/purchasing";
import { mockSuppliers } from "./suppliers";

export const mockWarehouseReceivingReports: WarehouseReceivingReport[] = [
  {
    id: "WRR-001",
    wrrNumber: "WRR-2025-001",
    poId: "PO-001",
    poNumber: "PO-2025-001",
    date: new Date("2025-10-24"),
    supplier: mockSuppliers[0],
    location: "Main Pharmacy Storage",
    status: "completed",
    items: [
      {
        id: "WRRI-001",
        itemName: "Paracetamol 500mg Tablets",
        itemCode: "MED-001",
        orderedQuantity: 1000,
        receivedQuantity: 1000,
        remainingQuantity: 0,
        unit: "tablets",
        expiryDate: new Date("2027-06-30"),
        batchNumber: "PARA2025-A01",
        remarks: "All items in good condition",
      },
      {
        id: "WRRI-002",
        itemName: "Amoxicillin 500mg Capsules",
        itemCode: "MED-002",
        orderedQuantity: 500,
        receivedQuantity: 500,
        remainingQuantity: 0,
        unit: "capsules",
        expiryDate: new Date("2027-05-15"),
        batchNumber: "AMOX2025-B01",
        remarks: "All items in good condition",
      },
    ],
    receivedBy: "GSO Staff Carmen Lopez",
    total: 1926.40,
    hasDiscrepancy: false,
    remarks: "Complete delivery, no issues",
    createdAt: new Date("2025-10-24"),
    updatedAt: new Date("2025-10-24"),
    createdBy: "Juan Dela Cruz",
    approver: "Maria Reyes",
  },
  {
    id: "WRR-002",
    wrrNumber: "WRR-2025-002",
    poId: "PO-002",
    poNumber: "PO-2025-002",
    date: new Date("2025-10-28"),
    supplier: mockSuppliers[1],
    location: "TB Program Storage",
    status: "receiving",
    items: [
      {
        id: "WRRI-003",
        itemName: "Rifampicin 150mg Tablets",
        itemCode: "MED-005",
        orderedQuantity: 2000,
        receivedQuantity: 1500,
        remainingQuantity: 500,
        unit: "tablets",
        expiryDate: new Date("2027-12-31"),
        batchNumber: "RIFA2025-C01",
        remarks: "Partial delivery",
      },
      {
        id: "WRRI-004",
        itemName: "Isoniazid 300mg Tablets",
        itemCode: "MED-006",
        orderedQuantity: 2000,
        receivedQuantity: 1500,
        remainingQuantity: 500,
        unit: "tablets",
        expiryDate: new Date("2027-11-30"),
        batchNumber: "ISON2025-D01",
        remarks: "Partial delivery",
      },
    ],
    receivedBy: "GSO Staff Carmen Lopez",
    total: 7560.00,
    hasDiscrepancy: true,
    discrepancyNotes: "Partial delivery - remaining items expected next week",
    remarks: "Supplier notified of balance",
    createdAt: new Date("2025-10-28"),
    updatedAt: new Date("2025-10-28"),
    createdBy: "Anna Santos",
    approver: "Pedro Mendoza",
  },
];

